### ISSUE TITLE
[BUG?] in SWITCH + LS mode , left direction will out DP direction down

### ISSUE THREAD

**Issue by xboxgod** [OpenStickCommunity/GP2040-CE#38] opened 2023-01-04 10:41 UTC
in 0.53 ver if set to LS + switch mode on pc, up down right is no problem, 
but left  will same time out DP direction down

**Comment by TheTrainGoes** [comment] 2023-01-04 14:48
Hi @xboxgod,

I tested this on v0.6.0 and am unable to reproduce on either the Switch directly on in Switch mode on a PC (Windows 10).  

Can you please test on v0.6.0 and let me know if you can reproduce the same behaviour?

If you can, please include more information about the setup you are using.

**Comment by deeebug** [comment] 2023-01-05 01:41
There's some weird stuff going on with Steam input support turned on, perhaps try checking with that turned off.

**Comment by xboxgod** [comment] 2023-01-10 12:49
I didnt use Switch test this bug, I use Open Joystick Display test, and same problem on 
gamepad-tester.com

**Comment by TheTrainGoes** [comment] 2023-01-10 14:16
@xboxgod - to confirm, you have been able to replicate this on multiple versions of the firmware?

**Comment by TheTrainGoes** [comment] 2023-01-13 16:27
@xboxgod following up on this.  Does it only occur in Steam?

**Comment by xboxgod** [comment] 2023-01-13 17:18
Not actually a STEAM platform, I just only test mode with gamepad-tester.com & Open Joystick Display software.
Because other chips will not have such an error output.

**Comment by xboxgod** [comment] 2023-01-15 07:49
and I test again, 0.52 not have this problem.

0.53 have LS LEFT same time output DP DOWN and 0.60 ver is same problem.

**Comment by TheTrainGoes** [comment] 2023-01-15 12:59
Can you please post a video or screen capture of the issue?

**Comment by xboxgod** [comment] 2023-01-19 07:17
![BUG1 - Switch](https://user-images.githubusercontent.com/108518244/213378809-9277c78b-d688-4bd4-a48a-4d9aaf12731c.png)

![BUG2 - DINPUT](https://user-images.githubusercontent.com/108518244/213378843-2bf10414-06ed-4352-ba6e-fad2fae403eb.png)

in 0.5.3 and 0.6 two of version SWITCH and DINPUT mode all have this problem , LS + LEFT direction will same time output DP DOWN;

but 0.5.2 all mode & 0.6 XINPUT is not have this problem. just like this:
![BUG2 - XINPUT NO BUG](https://user-images.githubusercontent.com/108518244/213379240-678f9524-75e7-4bd1-853a-3708c93b78a1.png)

**Comment by troytroy22** [comment] 2023-01-21 12:39
I could not replicate this issue even with both software shown with latest 0.6.0 firmware on Windows 10. Are multiple controllers showing up in Windows Game Controllers? Did you Flash Nuke The Pico before flashing of new firmware? I wonder if Dual Inputs are enabled or glitching from an old webconfig profile.

**Comment by xboxgod** [comment] 2023-01-22 08:33
I used windows 7 pro version, I didnt test one win11 or win10.
and I make sure just only one controller on pc
and every flash uf2 file, I am sure use nuke clearn uf2 file to clearn flash.

**Comment by TheTrainGoes** [comment] 2023-01-22 14:44
I am still not able to replicate this issue.  Do you have any other addons enabled?

**Comment by TheTrainGoes** [comment] 2023-02-14 20:46
I am going to close this as we have not been able to replicate.  

@xboxgod if you can replicate the issue on v0.6.1 please make a new issue and we can check it out.

**Comment by xboxgod** [comment] 2023-02-25 21:18
yes I tested on 0.6.1 Bug is gone, very nice, Thanks !

**Closed** 2023-02-25 21:35 UTC
Labels: bug
